/* eslint-disable react/no-danger */
import React, { useEffect, useState } from 'react';
import md2Json from 'md-2-json';

import Layout from '../components/layout';
import Link from '../components/Link';
import ConstrainedContainer from '../components/sections/ConstrainedContainer';
import SEO from '../components/seo';

const ChangelogPage = () => {
  const [data, setData] = useState();
  useEffect(() => {
    const fetchChangelogData = async () => {
      const response = await (
        await fetch(
          'https://raw.githubusercontent.com/AtomicCodeLabs/chummy/extension/prod/extension/CHANGELOG.md?token=ADGWG2VQLULKJNG2ZH5GYKDAICB56'
        )
      ).text();
      const { raw, ...sectionData } = md2Json.parse(response)?.Changelog;
      setData(sectionData);
    };
    fetchChangelogData();
  }, []);

  return (
    <Layout
      // isSimpleNavbar
      mainClassName="min-h-screen h-full bg-blue-50"
      innerMainClassName="justify-start items-center"
      navbarBgColor="bg-blue-50"
      navbarSecondaryBgColor="bg-white"
      fitFooter
    >
      <SEO title="Changelog" />

      <ConstrainedContainer>
        <h1 className="font-mono"># Changelog</h1>
        <p className="mt-8 mb-4 font-mono">
          This changelog is autogenerated from commits and follows semantic
          versioning practices. See{' '}
          <Link to="https://github.com/conventional-changelog/standard-version">
            standard-version
          </Link>{' '}
          for more information.
        </p>
        {data &&
          Object.entries(data).map(([version, { raw, ...content }]) => (
            <React.Fragment key={version}>
              <h3 className="font-mono" id={version}>
                ## {version}
              </h3>
              <p className="font-mono">{raw}</p>
              {content?.Features && (
                <>
                  <h4 className="font-mono">### Features</h4>
                  <p className="font-mono">{content?.Features}</p>
                </>
              )}
              {content?.['Bug Fixes'] && (
                <>
                  <h4 className="font-mono">### Bug Fixes</h4>
                  <p className="font-mono">{content?.['Bug Fixes']}</p>
                </>
              )}
            </React.Fragment>
          ))}
      </ConstrainedContainer>
    </Layout>
  );
};

export default ChangelogPage;
