export const popularLanguages = [
  { name: 'C', color: '#555555', language_id: 41, popular: true },
  { name: 'C#', color: '#178600', language_id: 42, popular: true },
  { name: 'C++', color: '#f34b7d', language_id: 43, popular: true },
  { name: 'CSS', color: '#563d7c', language_id: 50, popular: true },
  { name: 'CoffeeScript', color: '#244776', language_id: 63, popular: true },
  { name: 'DM', color: '#447265', language_id: 83, popular: true },
  { name: 'Dart', color: '#00B4AB', language_id: 87, popular: true },
  { name: 'Elixir', color: '#6e4a7e', language_id: 100, popular: true },
  { name: 'Go', color: '#00ADD8', language_id: 132, popular: true },
  { name: 'Groovy', color: '#e69f56', language_id: 142, popular: true },
  { name: 'HTML', color: '#e34c26', language_id: 146, popular: true },
  { name: 'Java', color: '#b07219', language_id: 181, popular: true },
  { name: 'JavaScript', color: '#f1e05a', language_id: 183, popular: true },
  { name: 'Kotlin', color: '#F18E33', language_id: 189, popular: true },
  { name: 'Objective-C', color: '#438eff', language_id: 257, popular: true },
  { name: 'PHP', color: '#4F5D95', language_id: 272, popular: true },
  { name: 'Perl', color: '#0298c3', language_id: 282, popular: true },
  { name: 'Python', color: '#3572A5', language_id: 303, popular: true },
  { name: 'Ruby', color: '#701516', language_id: 326, popular: true },
  { name: 'Scala', color: '#c22d40', language_id: 341, popular: true },
  { name: 'Shell', color: '#89e051', language_id: 346, popular: true },
  { name: 'Swift', color: '#ffac45', language_id: 362, popular: true },
  { name: 'TypeScript', color: '#2b7489', language_id: 378, popular: true }
];

export const otherLanguages = [
  { name: '1C Enterprise', color: '#814CCC', language_id: 0, popular: false },
  { name: '4D', language_id: 577529595, popular: false },
  { name: 'ABAP', color: '#E8274B', language_id: 1, popular: false },
  { name: 'ABNF', language_id: 429, popular: false },
  { name: 'AGS Script', color: '#B9D9FF', language_id: 2, popular: false },
  { name: 'AL', color: '#3AA2B5', language_id: 658971832, popular: false },
  { name: 'AMPL', color: '#E6EFBB', language_id: 3, popular: false },
  { name: 'ANTLR', color: '#9DC3FF', language_id: 4, popular: false },
  { name: 'API Blueprint', color: '#2ACCA8', language_id: 5, popular: false },
  { name: 'APL', color: '#5A8164', language_id: 6, popular: false },
  { name: 'ASL', language_id: 124996147, popular: false },
  { name: 'ASN.1', language_id: 7, popular: false },
  { name: 'ASP.NET', color: '#9400ff', language_id: 564186416, popular: false },
  { name: 'ATS', color: '#1ac620', language_id: 9, popular: false },
  { name: 'ActionScript', color: '#882B0F', language_id: 10, popular: false },
  { name: 'Ada', color: '#02f88c', language_id: 11, popular: false },
  { name: 'Adobe Font Metrics', language_id: 147198098, popular: false },
  { name: 'Agda', color: '#315665', language_id: 12, popular: false },
  { name: 'Alloy', color: '#64C800', language_id: 13, popular: false },
  { name: 'Alpine Abuild', language_id: 14, popular: false },
  { name: 'Altium Designer', language_id: 187772328, popular: false },
  {
    name: 'AngelScript',
    color: '#C7D7DC',
    language_id: 389477596,
    popular: false
  },
  { name: 'Ant Build System', language_id: 15, popular: false },
  { name: 'ApacheConf', language_id: 16, popular: false },
  { name: 'Apex', color: '#1797c0', language_id: 17, popular: false },
  {
    name: 'Apollo Guidance Computer',
    color: '#0B3D91',
    language_id: 18,
    popular: false
  },
  { name: 'AppleScript', color: '#101F1F', language_id: 19, popular: false },
  { name: 'Arc', color: '#aa2afe', language_id: 20, popular: false },
  { name: 'AsciiDoc', language_id: 22, popular: false },
  { name: 'AspectJ', color: '#a957b0', language_id: 23, popular: false },
  { name: 'Assembly', color: '#6E4C13', language_id: 24, popular: false },
  {
    name: 'Asymptote',
    color: '#ff0000',
    language_id: 591605007,
    popular: false
  },
  { name: 'Augeas', language_id: 25, popular: false },
  { name: 'AutoHotkey', color: '#6594b9', language_id: 26, popular: false },
  { name: 'AutoIt', color: '#1C3552', language_id: 27, popular: false },
  { name: 'Avro IDL', language_id: 785497837, popular: false },
  { name: 'Awk', language_id: 28, popular: false },
  {
    name: 'Ballerina',
    color: '#FF5000',
    language_id: 720859680,
    popular: false
  },
  { name: 'Batchfile', color: '#C1F12E', language_id: 29, popular: false },
  { name: 'Befunge', language_id: 30, popular: false },
  { name: 'BibTeX', language_id: 982188347, popular: false },
  { name: 'Bison', color: '#6A463F', language_id: 31, popular: false },
  { name: 'BitBake', language_id: 32, popular: false },
  { name: 'Blade', color: '#f7523f', language_id: 33, popular: false },
  { name: 'BlitzBasic', language_id: 34, popular: false },
  { name: 'BlitzMax', color: '#cd6400', language_id: 35, popular: false },
  { name: 'Bluespec', language_id: 36, popular: false },
  { name: 'Boo', color: '#d4bec1', language_id: 37, popular: false },
  { name: 'Brainfuck', color: '#2F2530', language_id: 38, popular: false },
  { name: 'Brightscript', language_id: 39, popular: false },
  { name: 'C-ObjDump', language_id: 44, popular: false },
  { name: 'C2hs Haskell', language_id: 45, popular: false },
  { name: 'CLIPS', language_id: 46, popular: false },
  { name: 'CMake', language_id: 47, popular: false },
  { name: 'COBOL', language_id: 48, popular: false },
  { name: 'COLLADA', language_id: 49, popular: false },
  { name: 'CSON', color: '#244776', language_id: 424, popular: false },
  { name: 'CSV', language_id: 51, popular: false },
  { name: 'CWeb', language_id: 657332628, popular: false },
  { name: 'Cabal Config', language_id: 677095381, popular: false },
  { name: "Cap'n Proto", language_id: 52, popular: false },
  { name: 'CartoCSS', language_id: 53, popular: false },
  { name: 'Ceylon', color: '#dfa535', language_id: 54, popular: false },
  { name: 'Chapel', color: '#8dc63f', language_id: 55, popular: false },
  { name: 'Charity', language_id: 56, popular: false },
  { name: 'ChucK', language_id: 57, popular: false },
  { name: 'Cirru', color: '#ccccff', language_id: 58, popular: false },
  { name: 'Clarion', color: '#db901e', language_id: 59, popular: false },
  { name: 'Classic ASP', color: '#6a40fd', language_id: 8, popular: false },
  { name: 'Clean', color: '#3F85AF', language_id: 60, popular: false },
  { name: 'Click', color: '#E4E6F3', language_id: 61, popular: false },
  { name: 'Clojure', color: '#db5855', language_id: 62, popular: false },
  { name: 'Closure Templates', language_id: 357046146, popular: false },
  {
    name: 'Cloud Firestore Security Rules',
    language_id: 407996372,
    popular: false
  },
  { name: 'CoNLL-U', language_id: 421026389, popular: false },
  { name: 'CodeQL', language_id: 424259634, popular: false },
  { name: 'ColdFusion', color: '#ed2cd6', language_id: 64, popular: false },
  { name: 'ColdFusion CFC', color: '#ed2cd6', language_id: 65, popular: false },
  { name: 'Common Lisp', color: '#3fb68b', language_id: 66, popular: false },
  {
    name: 'Common Workflow Language',
    color: '#B5314C',
    language_id: 988547172,
    popular: false
  },
  {
    name: 'Component Pascal',
    color: '#B0CE4E',
    language_id: 67,
    popular: false
  },
  { name: 'Cool', language_id: 68, popular: false },
  { name: 'Coq', language_id: 69, popular: false },
  { name: 'Cpp-ObjDump', language_id: 70, popular: false },
  { name: 'Creole', language_id: 71, popular: false },
  { name: 'Crystal', color: '#000100', language_id: 72, popular: false },
  { name: 'Csound', language_id: 73, popular: false },
  { name: 'Csound Document', language_id: 74, popular: false },
  { name: 'Csound Score', language_id: 75, popular: false },
  { name: 'Cuda', color: '#3A4E3A', language_id: 77, popular: false },
  { name: 'Cycript', language_id: 78, popular: false },
  { name: 'Cython', language_id: 79, popular: false },
  { name: 'D', color: '#ba595e', language_id: 80, popular: false },
  { name: 'D-ObjDump', language_id: 81, popular: false },
  { name: 'DIGITAL Command Language', language_id: 82, popular: false },
  { name: 'DNS Zone', language_id: 84, popular: false },
  { name: 'DTrace', language_id: 85, popular: false },
  { name: 'Dafny', color: '#FFEC25', language_id: 969323346, popular: false },
  { name: 'Darcs Patch', language_id: 86, popular: false },
  {
    name: 'DataWeave',
    color: '#003a52',
    language_id: 974514097,
    popular: false
  },
  { name: 'Dhall', color: '#dfafff', language_id: 793969321, popular: false },
  { name: 'Diff', language_id: 88, popular: false },
  { name: 'DirectX 3D File', language_id: 201049282, popular: false },
  { name: 'Dockerfile', color: '#384d54', language_id: 89, popular: false },
  { name: 'Dogescript', color: '#cca760', language_id: 90, popular: false },
  { name: 'Dylan', color: '#6c616e', language_id: 91, popular: false },
  { name: 'E', color: '#ccce35', language_id: 92, popular: false },
  { name: 'EBNF', language_id: 430, popular: false },
  { name: 'ECL', color: '#8a1267', language_id: 93, popular: false },
  { name: 'ECLiPSe', language_id: 94, popular: false },
  { name: 'EJS', color: '#a91e50', language_id: 95, popular: false },
  { name: 'EML', language_id: 529653389, popular: false },
  { name: 'EQ', color: '#a78649', language_id: 96, popular: false },
  { name: 'Eagle', language_id: 97, popular: false },
  { name: 'Easybuild', language_id: 342840477, popular: false },
  { name: 'Ecere Projects', language_id: 98, popular: false },
  { name: 'EditorConfig', language_id: 96139566, popular: false },
  { name: 'Edje Data Collection', language_id: 342840478, popular: false },
  { name: 'Eiffel', color: '#4d6977', language_id: 99, popular: false },
  { name: 'Elm', color: '#60B5CC', language_id: 101, popular: false },
  { name: 'Emacs Lisp', color: '#c065db', language_id: 102, popular: false },
  { name: 'EmberScript', color: '#FFF4F3', language_id: 103, popular: false },
  { name: 'Erlang', color: '#B83998', language_id: 104, popular: false },
  { name: 'F#', color: '#b845fc', language_id: 105, popular: false },
  { name: 'F*', color: '#572e30', language_id: 336943375, popular: false },
  { name: 'FIGlet Font', language_id: 686129783, popular: false },
  { name: 'FLUX', color: '#88ccff', language_id: 106, popular: false },
  { name: 'Factor', color: '#636746', language_id: 108, popular: false },
  { name: 'Fancy', color: '#7b9db4', language_id: 109, popular: false },
  { name: 'Fantom', color: '#14253c', language_id: 110, popular: false },
  { name: 'Faust', color: '#c37240', language_id: 622529198, popular: false },
  { name: 'Filebench WML', language_id: 111, popular: false },
  { name: 'Filterscript', language_id: 112, popular: false },
  { name: 'Formatted', language_id: 113, popular: false },
  { name: 'Forth', color: '#341708', language_id: 114, popular: false },
  { name: 'Fortran', color: '#4d41b1', language_id: 107, popular: false },
  { name: 'Fortran Free Form', language_id: 761352333, popular: false },
  { name: 'FreeMarker', color: '#0050b2', language_id: 115, popular: false },
  { name: 'Frege', color: '#00cafe', language_id: 116, popular: false },
  { name: 'Futhark', color: '#5f021f', language_id: 97358117, popular: false },
  { name: 'G-code', color: '#D08CF2', language_id: 117, popular: false },
  { name: 'GAML', color: '#FFC766', language_id: 290345951, popular: false },
  { name: 'GAMS', language_id: 118, popular: false },
  { name: 'GAP', language_id: 119, popular: false },
  { name: 'GCC Machine Description', language_id: 121, popular: false },
  { name: 'GDB', language_id: 122, popular: false },
  { name: 'GDScript', color: '#355570', language_id: 123, popular: false },
  { name: 'GEDCOM', language_id: 459577965, popular: false },
  { name: 'GLSL', language_id: 124, popular: false },
  { name: 'GN', language_id: 302957008, popular: false },
  {
    name: 'Game Maker Language',
    color: '#71b417',
    language_id: 125,
    popular: false
  },
  { name: 'Genie', color: '#fb855d', language_id: 792408528, popular: false },
  { name: 'Genshi', language_id: 126, popular: false },
  { name: 'Gentoo Ebuild', language_id: 127, popular: false },
  { name: 'Gentoo Eclass', language_id: 128, popular: false },
  { name: 'Gerber Image', language_id: 404627610, popular: false },
  { name: 'Gettext Catalog', language_id: 129, popular: false },
  { name: 'Gherkin', color: '#5B2063', language_id: 76, popular: false },
  { name: 'Git Attributes', language_id: 956324166, popular: false },
  { name: 'Git Config', language_id: 807968997, popular: false },
  { name: 'Glyph', color: '#c1ac7f', language_id: 130, popular: false },
  {
    name: 'Glyph Bitmap Distribution Format',
    language_id: 997665271,
    popular: false
  },
  { name: 'Gnuplot', color: '#f0a9f0', language_id: 131, popular: false },
  { name: 'Golo', color: '#88562A', language_id: 133, popular: false },
  { name: 'Gosu', color: '#82937f', language_id: 134, popular: false },
  { name: 'Grace', language_id: 135, popular: false },
  { name: 'Gradle', language_id: 136, popular: false },
  {
    name: 'Grammatical Framework',
    color: '#ff0000',
    language_id: 137,
    popular: false
  },
  { name: 'Graph Modeling Language', language_id: 138, popular: false },
  { name: 'GraphQL', color: '#e10098', language_id: 139, popular: false },
  { name: 'Graphviz (DOT)', language_id: 140, popular: false },
  { name: 'Groovy Server Pages', language_id: 143, popular: false },
  { name: 'HAProxy', language_id: 366607477, popular: false },
  { name: 'HCL', language_id: 144, popular: false },
  { name: 'HLSL', language_id: 145, popular: false },
  { name: 'HTML+Django', language_id: 147, popular: false },
  { name: 'HTML+ECR', language_id: 148, popular: false },
  { name: 'HTML+EEX', language_id: 149, popular: false },
  { name: 'HTML+ERB', language_id: 150, popular: false },
  { name: 'HTML+PHP', language_id: 151, popular: false },
  { name: 'HTML+Razor', language_id: 479039817, popular: false },
  { name: 'HTTP', language_id: 152, popular: false },
  { name: 'HXML', language_id: 786683730, popular: false },
  { name: 'Hack', color: '#878787', language_id: 153, popular: false },
  { name: 'Haml', color: '#ece2a9', language_id: 154, popular: false },
  { name: 'Handlebars', color: '#f7931e', language_id: 155, popular: false },
  { name: 'Harbour', color: '#0e60e3', language_id: 156, popular: false },
  { name: 'Haskell', color: '#5e5086', language_id: 157, popular: false },
  { name: 'Haxe', color: '#df7900', language_id: 158, popular: false },
  { name: 'HiveQL', color: '#dce200', language_id: 931814087, popular: false },
  { name: 'HolyC', color: '#ffefaf', language_id: 928121743, popular: false },
  { name: 'Hy', color: '#7790B2', language_id: 159, popular: false },
  { name: 'HyPhy', language_id: 160, popular: false },
  { name: 'IDL', color: '#a3522f', language_id: 161, popular: false },
  { name: 'IGOR Pro', color: '#0000cc', language_id: 162, popular: false },
  { name: 'INI', language_id: 163, popular: false },
  { name: 'IRC log', language_id: 164, popular: false },
  { name: 'Idris', color: '#b30000', language_id: 165, popular: false },
  { name: 'Ignore List', language_id: 74444240, popular: false },
  { name: 'Inform 7', language_id: 166, popular: false },
  { name: 'Inno Setup', language_id: 167, popular: false },
  { name: 'Io', color: '#a9188d', language_id: 168, popular: false },
  { name: 'Ioke', color: '#078193', language_id: 169, popular: false },
  { name: 'Isabelle', color: '#FEFE00', language_id: 170, popular: false },
  { name: 'Isabelle ROOT', language_id: 171, popular: false },
  { name: 'J', color: '#9EEDFF', language_id: 172, popular: false },
  { name: 'JFlex', color: '#DBCA00', language_id: 173, popular: false },
  { name: 'JSON', language_id: 174, popular: false },
  { name: 'JSON with Comments', language_id: 423, popular: false },
  { name: 'JSON5', language_id: 175, popular: false },
  { name: 'JSONLD', language_id: 176, popular: false },
  { name: 'JSONiq', color: '#40d47e', language_id: 177, popular: false },
  { name: 'JSX', language_id: 178, popular: false },
  { name: 'Jasmin', language_id: 180, popular: false },
  { name: 'Java Properties', language_id: 519377561, popular: false },
  { name: 'Java Server Pages', language_id: 182, popular: false },
  { name: 'JavaScript+ERB', language_id: 914318960, popular: false },
  { name: 'Jison', language_id: 284531423, popular: false },
  { name: 'Jison Lex', language_id: 406395330, popular: false },
  { name: 'Jolie', color: '#843179', language_id: 998078858, popular: false },
  { name: 'Jsonnet', color: '#0064bd', language_id: 664885656, popular: false },
  { name: 'Julia', color: '#a270ba', language_id: 184, popular: false },
  {
    name: 'Jupyter Notebook',
    color: '#DA5B0B',
    language_id: 185,
    popular: false
  },
  { name: 'KRL', color: '#28430A', language_id: 186, popular: false },
  {
    name: 'Kaitai Struct',
    color: '#773b37',
    language_id: 818804755,
    popular: false
  },
  { name: 'KiCad Layout', language_id: 187, popular: false },
  { name: 'KiCad Legacy Layout', language_id: 140848857, popular: false },
  { name: 'KiCad Schematic', language_id: 622447435, popular: false },
  { name: 'Kit', language_id: 188, popular: false },
  { name: 'LFE', color: '#4C3023', language_id: 190, popular: false },
  { name: 'LLVM', color: '#185619', language_id: 191, popular: false },
  { name: 'LOLCODE', color: '#cc9900', language_id: 192, popular: false },
  { name: 'LSL', color: '#3d9970', language_id: 193, popular: false },
  { name: 'LTspice Symbol', language_id: 1013566805, popular: false },
  { name: 'LabVIEW', language_id: 194, popular: false },
  { name: 'Lark', color: '#0b130f', language_id: 758480799, popular: false },
  { name: 'Lasso', color: '#999999', language_id: 195, popular: false },
  { name: 'Latte', color: '#f2a542', language_id: 196, popular: false },
  { name: 'Lean', language_id: 197, popular: false },
  { name: 'Less', color: '#1d365d', language_id: 198, popular: false },
  { name: 'Lex', color: '#DBCA00', language_id: 199, popular: false },
  { name: 'LilyPond', language_id: 200, popular: false },
  { name: 'Limbo', language_id: 201, popular: false },
  { name: 'Linker Script', language_id: 202, popular: false },
  { name: 'Linux Kernel Module', language_id: 203, popular: false },
  { name: 'Liquid', language_id: 204, popular: false },
  { name: 'Literate Agda', language_id: 205, popular: false },
  { name: 'Literate CoffeeScript', language_id: 206, popular: false },
  { name: 'Literate Haskell', language_id: 207, popular: false },
  { name: 'LiveScript', color: '#499886', language_id: 208, popular: false },
  { name: 'Logos', language_id: 209, popular: false },
  { name: 'Logtalk', language_id: 210, popular: false },
  { name: 'LookML', color: '#652B81', language_id: 211, popular: false },
  { name: 'LoomScript', language_id: 212, popular: false },
  { name: 'Lua', color: '#000080', language_id: 213, popular: false },
  { name: 'M', language_id: 214, popular: false },
  { name: 'M4', language_id: 215, popular: false },
  { name: 'M4Sugar', language_id: 216, popular: false },
  { name: 'MATLAB', color: '#e16737', language_id: 225, popular: false },
  { name: 'MAXScript', color: '#00a6a6', language_id: 217, popular: false },
  { name: 'MLIR', color: '#5EC8DB', language_id: 448253929, popular: false },
  { name: 'MQL4', color: '#62A8D6', language_id: 426, popular: false },
  { name: 'MQL5', color: '#4A76B8', language_id: 427, popular: false },
  { name: 'MTML', color: '#b7e1f4', language_id: 218, popular: false },
  { name: 'MUF', language_id: 219, popular: false },
  {
    name: 'Macaulay2',
    color: '#d8ffff',
    language_id: 34167825,
    popular: false
  },
  { name: 'Makefile', color: '#427819', language_id: 220, popular: false },
  { name: 'Mako', language_id: 221, popular: false },
  { name: 'Markdown', color: '#083fa1', language_id: 222, popular: false },
  { name: 'Marko', color: '#42bff2', language_id: 932782397, popular: false },
  { name: 'Mask', color: '#f97732', language_id: 223, popular: false },
  { name: 'Mathematica', language_id: 224, popular: false },
  { name: 'Maven POM', language_id: 226, popular: false },
  { name: 'Max', color: '#c4a79c', language_id: 227, popular: false },
  { name: 'MediaWiki', language_id: 228, popular: false },
  { name: 'Mercury', color: '#ff2b2b', language_id: 229, popular: false },
  { name: 'Meson', color: '#007800', language_id: 799141244, popular: false },
  { name: 'Metal', color: '#8f14e9', language_id: 230, popular: false },
  {
    name: 'Microsoft Developer Studio Project',
    language_id: 800983837,
    popular: false
  },
  { name: 'MiniD', language_id: 231, popular: false },
  { name: 'Mirah', color: '#c7a938', language_id: 232, popular: false },
  { name: 'Modelica', language_id: 233, popular: false },
  { name: 'Modula-2', language_id: 234, popular: false },
  {
    name: 'Modula-3',
    color: '#223388',
    language_id: 564743864,
    popular: false
  },
  { name: 'Module Management System', language_id: 235, popular: false },
  { name: 'Monkey', language_id: 236, popular: false },
  { name: 'Moocode', language_id: 237, popular: false },
  { name: 'MoonScript', language_id: 238, popular: false },
  { name: 'Motorola 68K Assembly', language_id: 477582706, popular: false },
  { name: 'Muse', language_id: 474864066, popular: false },
  { name: 'Mustache', language_id: 638334590, popular: false },
  { name: 'Myghty', language_id: 239, popular: false },
  { name: 'NASL', language_id: 171666519, popular: false },
  { name: 'NCL', color: '#28431f', language_id: 240, popular: false },
  { name: 'NEON', language_id: 481192983, popular: false },
  { name: 'NL', language_id: 241, popular: false },
  { name: 'NPM Config', language_id: 685022663, popular: false },
  { name: 'NSIS', language_id: 242, popular: false },
  { name: 'Nearley', color: '#990000', language_id: 521429430, popular: false },
  { name: 'Nemerle', color: '#3d3c6e', language_id: 243, popular: false },
  { name: 'NetLinx', color: '#0aa0ff', language_id: 244, popular: false },
  { name: 'NetLinx+ERB', color: '#747faa', language_id: 245, popular: false },
  { name: 'NetLogo', color: '#ff6375', language_id: 246, popular: false },
  { name: 'NewLisp', color: '#87AED7', language_id: 247, popular: false },
  {
    name: 'Nextflow',
    color: '#3ac486',
    language_id: 506780613,
    popular: false
  },
  { name: 'Nginx', language_id: 248, popular: false },
  { name: 'Nim', color: '#ffc200', language_id: 249, popular: false },
  { name: 'Ninja', language_id: 250, popular: false },
  { name: 'Nit', color: '#009917', language_id: 251, popular: false },
  { name: 'Nix', color: '#7e7eff', language_id: 252, popular: false },
  { name: 'Nu', color: '#c9df40', language_id: 253, popular: false },
  { name: 'NumPy', color: '#9C8AF9', language_id: 254, popular: false },
  { name: 'OCaml', color: '#3be133', language_id: 255, popular: false },
  { name: 'ObjDump', language_id: 256, popular: false },
  {
    name: 'Object Data Instance Notation',
    language_id: 985227236,
    popular: false
  },
  {
    name: 'ObjectScript',
    color: '#424893',
    language_id: 202735509,
    popular: false
  },
  { name: 'Objective-C++', color: '#6866fb', language_id: 258, popular: false },
  { name: 'Objective-J', color: '#ff0c5a', language_id: 259, popular: false },
  { name: 'Odin', color: '#60AFFE', language_id: 889244082, popular: false },
  { name: 'Omgrofl', color: '#cabbff', language_id: 260, popular: false },
  { name: 'Opa', language_id: 261, popular: false },
  { name: 'Opal', color: '#f7ede0', language_id: 262, popular: false },
  { name: 'Open Policy Agent', language_id: 840483232, popular: false },
  { name: 'OpenCL', language_id: 263, popular: false },
  { name: 'OpenEdge ABL', language_id: 264, popular: false },
  {
    name: 'OpenQASM',
    color: '#AA70FF',
    language_id: 153739399,
    popular: false
  },
  { name: 'OpenRC runscript', language_id: 265, popular: false },
  { name: 'OpenSCAD', language_id: 266, popular: false },
  { name: 'OpenStep Property List', language_id: 598917541, popular: false },
  { name: 'OpenType Feature File', language_id: 374317347, popular: false },
  { name: 'Org', language_id: 267, popular: false },
  { name: 'Ox', language_id: 268, popular: false },
  { name: 'Oxygene', color: '#cdd0e3', language_id: 269, popular: false },
  { name: 'Oz', color: '#fab738', language_id: 270, popular: false },
  { name: 'P4', color: '#7055b5', language_id: 348895984, popular: false },
  { name: 'PLSQL', color: '#dad8d8', language_id: 273, popular: false },
  { name: 'PLpgSQL', language_id: 274, popular: false },
  { name: 'POV-Ray SDL', language_id: 275, popular: false },
  { name: 'Pan', color: '#cc0000', language_id: 276, popular: false },
  { name: 'Papyrus', color: '#6600cc', language_id: 277, popular: false },
  { name: 'Parrot', color: '#f3ca0a', language_id: 278, popular: false },
  { name: 'Parrot Assembly', language_id: 279, popular: false },
  { name: 'Parrot Internal Representation', language_id: 280, popular: false },
  { name: 'Pascal', color: '#E3F171', language_id: 281, popular: false },
  { name: 'Pawn', color: '#dbb284', language_id: 271, popular: false },
  { name: 'Pep8', color: '#C76F5B', language_id: 840372442, popular: false },
  { name: 'Pic', language_id: 425, popular: false },
  { name: 'Pickle', language_id: 284, popular: false },
  { name: 'PicoLisp', language_id: 285, popular: false },
  { name: 'PigLatin', color: '#fcd7de', language_id: 286, popular: false },
  { name: 'Pike', color: '#005390', language_id: 287, popular: false },
  { name: 'PlantUML', language_id: 833504686, popular: false },
  { name: 'Pod', language_id: 288, popular: false },
  { name: 'Pod 6', language_id: 155357471, popular: false },
  { name: 'PogoScript', color: '#d80074', language_id: 289, popular: false },
  { name: 'Pony', language_id: 290, popular: false },
  { name: 'PostCSS', language_id: 262764437, popular: false },
  { name: 'PostScript', color: '#da291c', language_id: 291, popular: false },
  { name: 'PowerBuilder', color: '#8f0f8d', language_id: 292, popular: false },
  { name: 'PowerShell', color: '#012456', language_id: 293, popular: false },
  { name: 'Prisma', color: '#0c344b', language_id: 499933428, popular: false },
  { name: 'Processing', color: '#0096D8', language_id: 294, popular: false },
  { name: 'Proguard', language_id: 716513858, popular: false },
  { name: 'Prolog', color: '#74283c', language_id: 295, popular: false },
  {
    name: 'Propeller Spin',
    color: '#7fa2a7',
    language_id: 296,
    popular: false
  },
  { name: 'Protocol Buffer', language_id: 297, popular: false },
  { name: 'Public Key', language_id: 298, popular: false },
  { name: 'Pug', color: '#a86454', language_id: 179, popular: false },
  { name: 'Puppet', color: '#302B6D', language_id: 299, popular: false },
  { name: 'Pure Data', language_id: 300, popular: false },
  { name: 'PureBasic', color: '#5a6986', language_id: 301, popular: false },
  { name: 'PureScript', color: '#1D222D', language_id: 302, popular: false },
  { name: 'Python console', language_id: 428, popular: false },
  { name: 'Python traceback', language_id: 304, popular: false },
  { name: 'Q#', color: '#fed659', language_id: 697448245, popular: false },
  { name: 'QML', color: '#44a51c', language_id: 305, popular: false },
  { name: 'QMake', language_id: 306, popular: false },
  {
    name: 'Qt Script',
    color: '#00b841',
    language_id: 558193693,
    popular: false
  },
  { name: 'Quake', color: '#882233', language_id: 375265331, popular: false },
  { name: 'R', color: '#198CE7', language_id: 307, popular: false },
  { name: 'RAML', color: '#77d9fb', language_id: 308, popular: false },
  { name: 'RDoc', language_id: 309, popular: false },
  { name: 'REALbasic', language_id: 310, popular: false },
  { name: 'REXX', language_id: 311, popular: false },
  { name: 'RMarkdown', language_id: 313, popular: false },
  { name: 'RPC', language_id: 1031374237, popular: false },
  { name: 'RPM Spec', language_id: 314, popular: false },
  { name: 'RUNOFF', color: '#665a4e', language_id: 315, popular: false },
  { name: 'Racket', color: '#3c5caa', language_id: 316, popular: false },
  { name: 'Ragel', color: '#9d5200', language_id: 317, popular: false },
  { name: 'Raku', color: '#0000fb', language_id: 283, popular: false },
  { name: 'Rascal', color: '#fffaa0', language_id: 173616037, popular: false },
  { name: 'Raw token data', language_id: 318, popular: false },
  { name: 'Readline Config', language_id: 538732839, popular: false },
  { name: 'Reason', color: '#ff5847', language_id: 869538413, popular: false },
  { name: 'Rebol', color: '#358a5b', language_id: 319, popular: false },
  { name: 'Red', color: '#f50000', language_id: 320, popular: false },
  { name: 'Redcode', language_id: 321, popular: false },
  { name: 'Regular Expression', language_id: 363378884, popular: false },
  { name: "Ren'Py", color: '#ff7f7f', language_id: 322, popular: false },
  { name: 'RenderScript', language_id: 323, popular: false },
  { name: 'Rich Text Format', language_id: 51601661, popular: false },
  { name: 'Ring', color: '#2D54CB', language_id: 431, popular: false },
  { name: 'Riot', color: '#A71E49', language_id: 878396783, popular: false },
  { name: 'RobotFramework', language_id: 324, popular: false },
  { name: 'Roff', color: '#ecdebe', language_id: 141, popular: false },
  { name: 'Roff Manpage', language_id: 612669833, popular: false },
  { name: 'Rouge', color: '#cc0088', language_id: 325, popular: false },
  { name: 'Rust', color: '#dea584', language_id: 327, popular: false },
  { name: 'SAS', color: '#B34936', language_id: 328, popular: false },
  { name: 'SCSS', color: '#c6538c', language_id: 329, popular: false },
  { name: 'SMT', language_id: 330, popular: false },
  { name: 'SPARQL', language_id: 331, popular: false },
  { name: 'SQF', color: '#3F3F3F', language_id: 332, popular: false },
  { name: 'SQL', language_id: 333, popular: false },
  { name: 'SQLPL', language_id: 334, popular: false },
  {
    name: 'SRecode Template',
    color: '#348a34',
    language_id: 335,
    popular: false
  },
  { name: 'SSH Config', language_id: 554920715, popular: false },
  { name: 'STON', language_id: 336, popular: false },
  { name: 'SVG', color: '#ff9900', language_id: 337, popular: false },
  { name: 'SWIG', language_id: 1066250075, popular: false },
  { name: 'Sage', language_id: 338, popular: false },
  { name: 'SaltStack', color: '#646464', language_id: 339, popular: false },
  { name: 'Sass', color: '#a53b70', language_id: 340, popular: false },
  { name: 'Scaml', language_id: 342, popular: false },
  { name: 'Scheme', color: '#1e4aec', language_id: 343, popular: false },
  { name: 'Scilab', language_id: 344, popular: false },
  { name: 'Self', color: '#0579aa', language_id: 345, popular: false },
  { name: 'ShaderLab', language_id: 664257356, popular: false },
  { name: 'ShellSession', language_id: 347, popular: false },
  { name: 'Shen', color: '#120F14', language_id: 348, popular: false },
  { name: 'Sieve', language_id: 208976687, popular: false },
  { name: 'Slash', color: '#007eff', language_id: 349, popular: false },
  { name: 'Slice', color: '#003fa2', language_id: 894641667, popular: false },
  { name: 'Slim', color: '#2b2b2b', language_id: 350, popular: false },
  { name: 'SmPL', color: '#c94949', language_id: 164123055, popular: false },
  { name: 'Smali', language_id: 351, popular: false },
  { name: 'Smalltalk', color: '#596706', language_id: 352, popular: false },
  { name: 'Smarty', language_id: 353, popular: false },
  {
    name: 'Solidity',
    color: '#AA6746',
    language_id: 237469032,
    popular: false
  },
  { name: 'SourcePawn', color: '#f69e1d', language_id: 354, popular: false },
  { name: 'Spline Font Database', language_id: 767169629, popular: false },
  { name: 'Squirrel', color: '#800000', language_id: 355, popular: false },
  { name: 'Stan', color: '#b2011d', language_id: 356, popular: false },
  { name: 'Standard ML', color: '#dc566d', language_id: 357, popular: false },
  {
    name: 'Starlark',
    color: '#76d275',
    language_id: 960266174,
    popular: false
  },
  { name: 'Stata', language_id: 358, popular: false },
  { name: 'Stylus', color: '#ff6347', language_id: 359, popular: false },
  { name: 'SubRip Text', language_id: 360, popular: false },
  { name: 'SugarSS', language_id: 826404698, popular: false },
  { name: 'SuperCollider', color: '#46390b', language_id: 361, popular: false },
  { name: 'Svelte', color: '#ff3e00', language_id: 928734530, popular: false },
  { name: 'SystemVerilog', color: '#DAE1C2', language_id: 363, popular: false },
  { name: 'TI Program', color: '#A0AA87', language_id: 422, popular: false },
  { name: 'TLA', language_id: 364, popular: false },
  { name: 'TOML', language_id: 365, popular: false },
  { name: 'TSQL', language_id: 918334941, popular: false },
  { name: 'TSV', language_id: 1035892117, popular: false },
  { name: 'TSX', language_id: 94901924, popular: false },
  { name: 'TXL', language_id: 366, popular: false },
  { name: 'Tcl', color: '#e4cc98', language_id: 367, popular: false },
  { name: 'Tcsh', language_id: 368, popular: false },
  { name: 'TeX', color: '#3D6117', language_id: 369, popular: false },
  { name: 'Tea', language_id: 370, popular: false },
  { name: 'Terra', color: '#00004c', language_id: 371, popular: false },
  { name: 'Texinfo', language_id: 988020015, popular: false },
  { name: 'Text', language_id: 372, popular: false },
  { name: 'Textile', language_id: 373, popular: false },
  { name: 'Thrift', language_id: 374, popular: false },
  { name: 'Turing', color: '#cf142b', language_id: 375, popular: false },
  { name: 'Turtle', language_id: 376, popular: false },
  { name: 'Twig', color: '#c1d026', language_id: 377, popular: false },
  { name: 'Type Language', language_id: 632765617, popular: false },
  {
    name: 'Unified Parallel C',
    color: '#4e3617',
    language_id: 379,
    popular: false
  },
  { name: 'Unity3D Asset', language_id: 380, popular: false },
  { name: 'Unix Assembly', language_id: 120, popular: false },
  { name: 'Uno', color: '#9933cc', language_id: 381, popular: false },
  { name: 'UnrealScript', color: '#a54c4d', language_id: 382, popular: false },
  { name: 'UrWeb', language_id: 383, popular: false },
  { name: 'V', color: '#4f87c4', language_id: 603371597, popular: false },
  { name: 'VBA', color: '#867db1', language_id: 399230729, popular: false },
  {
    name: 'VBScript',
    color: '#15dcdc',
    language_id: 408016005,
    popular: false
  },
  { name: 'VCL', color: '#148AA8', language_id: 384, popular: false },
  { name: 'VHDL', color: '#adb2cb', language_id: 385, popular: false },
  { name: 'Vala', color: '#fbe5cd', language_id: 386, popular: false },
  { name: 'Verilog', color: '#b2b7f8', language_id: 387, popular: false },
  { name: 'Vim Help File', language_id: 508563686, popular: false },
  { name: 'Vim Snippet', language_id: 81265970, popular: false },
  { name: 'Vim script', color: '#199f4b', language_id: 388, popular: false },
  {
    name: 'Visual Basic .NET',
    color: '#945db7',
    language_id: 389,
    popular: false
  },
  { name: 'Volt', color: '#1F1F1F', language_id: 390, popular: false },
  { name: 'Vue', color: '#2c3e50', language_id: 391, popular: false },
  { name: 'Wavefront Material', language_id: 392, popular: false },
  { name: 'Wavefront Object', language_id: 393, popular: false },
  { name: 'Web Ontology Language', language_id: 394, popular: false },
  {
    name: 'WebAssembly',
    color: '#04133b',
    language_id: 956556503,
    popular: false
  },
  { name: 'WebIDL', language_id: 395, popular: false },
  { name: 'WebVTT', language_id: 658679714, popular: false },
  { name: 'Wget Config', language_id: 668457123, popular: false },
  { name: 'Windows Registry Entries', language_id: 969674868, popular: false },
  { name: 'Wollok', color: '#a23738', language_id: 632745969, popular: false },
  { name: 'World of Warcraft Addon Data', language_id: 396, popular: false },
  { name: 'X BitMap', language_id: 782911107, popular: false },
  { name: 'X Font Directory Index', language_id: 208700028, popular: false },
  { name: 'X PixMap', language_id: 781846279, popular: false },
  { name: 'X10', color: '#4B6BEF', language_id: 397, popular: false },
  { name: 'XC', color: '#99DA07', language_id: 398, popular: false },
  { name: 'XCompose', language_id: 225167241, popular: false },
  { name: 'XML', language_id: 399, popular: false },
  { name: 'XML Property List', language_id: 75622871, popular: false },
  { name: 'XPages', language_id: 400, popular: false },
  { name: 'XProc', language_id: 401, popular: false },
  { name: 'XQuery', color: '#5232e7', language_id: 402, popular: false },
  { name: 'XS', language_id: 403, popular: false },
  { name: 'XSLT', color: '#EB8CEB', language_id: 404, popular: false },
  { name: 'Xojo', language_id: 405, popular: false },
  { name: 'Xtend', language_id: 406, popular: false },
  { name: 'YAML', color: '#cb171e', language_id: 407, popular: false },
  { name: 'YANG', language_id: 408, popular: false },
  { name: 'YARA', color: '#220000', language_id: 805122868, popular: false },
  {
    name: 'YASnippet',
    color: '#32AB90',
    language_id: 378760102,
    popular: false
  },
  { name: 'Yacc', color: '#4B6C4B', language_id: 409, popular: false },
  { name: 'ZAP', color: '#0d665e', language_id: 952972794, popular: false },
  { name: 'ZIL', color: '#dc75e5', language_id: 973483626, popular: false },
  { name: 'Zeek', language_id: 40, popular: false },
  {
    name: 'ZenScript',
    color: '#00BCD1',
    language_id: 494938890,
    popular: false
  },
  { name: 'Zephir', color: '#118f9e', language_id: 410, popular: false },
  { name: 'Zig', color: '#ec915c', language_id: 646424281, popular: false },
  { name: 'Zimpl', language_id: 411, popular: false },
  { name: 'cURL Config', language_id: 992375436, popular: false },
  { name: 'desktop', language_id: 412, popular: false },
  { name: 'dircolors', language_id: 691605112, popular: false },
  { name: 'eC', color: '#913960', language_id: 413, popular: false },
  { name: 'edn', language_id: 414, popular: false },
  { name: 'fish', language_id: 415, popular: false },
  {
    name: 'mIRC Script',
    color: '#3d57c3',
    language_id: 517654727,
    popular: false
  },
  {
    name: 'mcfunction',
    color: '#E22837',
    language_id: 462488745,
    popular: false
  },
  { name: 'mupad', language_id: 416, popular: false },
  { name: 'nanorc', language_id: 775996197, popular: false },
  { name: 'nesC', color: '#94B0C7', language_id: 417, popular: false },
  { name: 'ooc', color: '#b0b77e', language_id: 418, popular: false },
  { name: 'q', color: '#0040cd', language_id: 970539067, popular: false },
  { name: 'reStructuredText', language_id: 419, popular: false },
  { name: 'sed', color: '#64b970', language_id: 847830017, popular: false },
  { name: 'wdl', color: '#42f1f4', language_id: 374521672, popular: false },
  { name: 'wisp', color: '#7582D1', language_id: 420, popular: false },
  { name: 'xBase', color: '#403a40', language_id: 421, popular: false }
];
