version: 0.2

env:
  variables:
    key: "value"
    key: "value"
  exported-variables:
    - variable
    - variable

proxy:
  upload-artifacts: no
  logs: no

batch:
  fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:
        
phases:
  pre_build:
    commands:
      - command
      - command
    finally:
      - command
      - command
  build:
    commands:
      - command
      - command
    finally:
      - command
      - command
  post_build:
    commands:
      - command
      - command
    finally:
      - command
      - command

reports:
    files:
      - location
      - location
    base-directory: location
    discard-paths: no | yes
    file-format: report-format

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - 'dist/moz/*'
      name: dist.moz
    artifact2:
      files:
        - 'dist/web/*'
      name: dist.web

cache:
  paths:
    - node_modules/**/*
