version: 0.2

env:
  variables:
    VERSION: "1.0.0"
    WEBSITE_SIGNIN: "signin/"
    WEBSITE_REDIRECT: "account/"
  parameter-store:
    ROOT_ACCESS_KEY_ID: "ROOT_ACCESS_KEY_ID"
    ROOT_SECRET_ACCESS_KEY: "ROOT_SECRET_ACCESS_KEY"

phases:
  pre_build:
    commands:
      - cd extension
      - REACTCONFIG="{\"SourceDir\":\"src\",\"DistributionDir\":\"dist\",\"BuildCommand\":\"yarn build:web\",\"StartCommand\":\"yarn dev\"}"
      - AWSCLOUDFORMATIONCONFIG="{\"configLevel\":\"project\",\"useProfile\":false,\"profileName\":\"default\",\"accessKeyId\":\"$ROOT_ACCESS_KEY_ID\",\"secretAccessKey\":\"$ROOT_SECRET_ACCESS_KEY\",\"region\":\"$AWS_DEFAULT_REGION\"}"
      - AMPLIFY="{\"projectName\":\"chummy\",\"appId\":\"d37x99ddsw850\",\"envName\":\"$STAGE\",\"defaultEditor\":\"code\"}"
      - FRONTEND="{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":$REACTCONFIG}"
      - PROVIDERS="{\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG}"
      - amplify init --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --yes
      - echo $CHUMMY_KEY_PEM > ./key.pem
      - yarn install --frozen-lockfile
      - yarn lint:check
      - yarn format:check
  build:
    commands:
      - yarn build:moz
      - yarn build:web

artifacts:
  base-directory: "extension/dist"
  files:
    - "**/*"
  secondary-artifacts:
    artifact1:
      files:
        - "moz/*"
      name: $VERSION/dist_$VERSION.moz
    artifact2:
      files:
        - "web/*"
      name: $VERSION/dist_$VERSION.web

cache:
  paths:
    - "extension/node_modules/**/*"
