version: 0.2

env:
  variables:
    WEBSITE_SIGNIN: "signin/"
    WEBSITE_REDIRECT: "account/"

proxy:
  upload-artifacts: no
  logs: no

phases:
  pre_build:
    commands:
      - cd extension
      - amplify pull --appId d37x99ddsw850 --envName $STAGE
      - echo $CHUMMY_KEY_PEM > ./key.pem
      - yarn install --frozen-lockfile
      - yarn lint:check
      - yarn format:check
  build:
    commands:
      - yarn build:moz
      - yarn build:web

artifacts:
  base-directory: "extension/dist"
  files:
    - "**/*"
  secondary-artifacts:
    artifact1:
      files:
        - "moz/*"
      name: dist.moz
    artifact2:
      files:
        - "web/*"
      name: dist.web

cache:
  paths:
    - "extension/node_modules/**/*"
