name: Build Website

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: website

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: website
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Decrypt env secret
        run: ../envs/decrypt_env.sh
        env:
          ENV_PRODUCTION_SECRET_KEY: ${{ secrets.ENV_PRODUCTION_SECRET_KEY }}
      - run: npm install -g yarn gatsby-cli
      - name: yarn install, check, and build
        run: |
          yarn
          gatsby build